/**
 * KWIN City — Global Search Index
 * ─────────────────────────────────
 * A fully-static, compile-time search corpus. Zero external dependencies.
 * Each SearchEntry is scored at query time in the SearchModal/search page;
 * the index can be regenerated by editing the arrays below or by importing
 * from the shared constants/config modules.
 *
 * Scoring model:
 *   • Exact title match               → weight 10
 *   • Title contains query word       → weight 7
 *   • Tag or category contains word   → weight 4
 *   • Description contains word       → weight 2
 */

export type SearchCategory =
  | 'Page'
  | 'Timeline'
  | 'Sector'
  | 'Sustainability'
  | 'Pillar'
  | 'FAQ'
  | 'Download'
  | 'Update'
  | 'Data';

export interface SearchEntry {
  id: string;
  title: string;
  description: string;
  category: SearchCategory;
  href: string;
  icon: string;
  tags: string[];
}

// ─── Pages ────────────────────────────────────────────────────────────────────
const PAGES: SearchEntry[] = [
  {
    id: 'page-home',
    title: 'KWIN City — Home',
    description: 'The definitive portal for KWIN City, North Bengaluru. Knowledge, Wellbeing, Innovation.',
    category: 'Page',
    href: '/',
    icon: '🏙️',
    tags: ['home', 'kwin', 'knowledge wellbeing innovation'],
  },
  {
    id: 'page-about',
    title: 'About KWIN City',
    description: 'Mission, pillars, and development framework for the 465-acre township.',
    category: 'Page',
    href: '/about',
    icon: 'ℹ️',
    tags: ['about', 'pillars', 'framework', 'township', 'doddaballapura'],
  },
  {
    id: 'page-region',
    title: 'Why North Bengaluru',
    description: 'Strategic location case: proximity to airport, STRR, and the Bengaluru–Mumbai corridor.',
    category: 'Page',
    href: '/why-north-bengaluru',
    icon: '📍',
    tags: ['north bengaluru', 'location', 'STRR', 'airport', 'strategic', 'region'],
  },
  {
    id: 'page-timeline',
    title: 'Development Timeline',
    description: 'Six-phase roadmap from 2024 inauguration to full operations by 2030.',
    category: 'Page',
    href: '/timeline',
    icon: '📅',
    tags: ['timeline', 'phases', 'milestones', '2024', '2030', 'roadmap'],
  },
  {
    id: 'page-sectors',
    title: 'Industry Sectors',
    description: 'Semiconductor, aerospace, health-tech, ICT, and renewable energy clusters.',
    category: 'Page',
    href: '/sectors',
    icon: '🏭',
    tags: ['sectors', 'industry', 'semiconductor', 'aerospace', 'ict', 'healthcare', 'renewable'],
  },
  {
    id: 'page-sustainability',
    title: 'Sustainability',
    description: 'Net-zero roadmap, green cover targets, water recycling, and biodiversity commitments.',
    category: 'Page',
    href: '/sustainability',
    icon: '🌱',
    tags: ['sustainability', 'green', 'net zero', 'carbon', 'water', 'renewable energy'],
  },
  {
    id: 'page-data',
    title: 'Data Insights Lab',
    description: 'Live charts and open data from OpenCity.in — aviation, demographics, infrastructure.',
    category: 'Page',
    href: '/data-insights',
    icon: '📊',
    tags: ['data', 'charts', 'opencity', 'insights', 'statistics', 'live'],
  },
  {
    id: 'page-evidence',
    title: 'Evidence Vault',
    description: 'What each dataset can and cannot prove about KWIN City claims.',
    category: 'Page',
    href: '/evidence',
    icon: '✓',
    tags: ['evidence', 'sources', 'verified', 'claims', 'proof', 'trust'],
  },
  {
    id: 'page-sources',
    title: 'Sources & Claims Ledger',
    description: 'Full audit trail mapping every claim on this portal to its source document.',
    category: 'Page',
    href: '/sources',
    icon: '📚',
    tags: ['sources', 'citations', 'claims', 'audit', 'ledger', 'references'],
  },
  {
    id: 'page-trust',
    title: 'Trust Center',
    description: 'KWIN City portal authenticity and transparency protocol.',
    category: 'Page',
    href: '/trust',
    icon: '🛡️',
    tags: ['trust', 'authenticity', 'transparency', 'protocol', 'editorial'],
  },
  {
    id: 'page-news',
    title: 'News Intelligence',
    description: 'Attribution-first media observatory tracking KWIN City coverage.',
    category: 'Page',
    href: '/news-intelligence',
    icon: '🗞️',
    tags: ['news', 'media', 'journalism', 'press', 'articles', 'coverage'],
  },
  {
    id: 'page-for',
    title: 'Audience Hubs',
    description: 'Tailored content pathways for investors, residents, researchers, journalists, and citizens.',
    category: 'Page',
    href: '/for',
    icon: '🧭',
    tags: ['persona', 'investor', 'resident', 'researcher', 'journalist', 'citizen'],
  },
  {
    id: 'page-investor',
    title: 'For Investors',
    description: 'Opportunity landscape, risk briefing, and investment pathways in KWIN City.',
    category: 'Page',
    href: '/for/investor',
    icon: '📈',
    tags: ['investor', 'investment', 'roi', 'opportunity', 'risk', 'land', 'industrial'],
  },
  {
    id: 'page-resident',
    title: 'For Residents',
    description: 'Livability index, future community facilities, and public participation.',
    category: 'Page',
    href: '/for/resident',
    icon: '🏡',
    tags: ['resident', 'home', 'community', 'livability', 'housing', 'amenities'],
  },
  {
    id: 'page-researcher',
    title: 'For Researchers',
    description: 'Open datasets, methodology notes, and primary source access.',
    category: 'Page',
    href: '/for/researcher',
    icon: '🔬',
    tags: ['researcher', 'data', 'methodology', 'academic', 'open data', 'citations'],
  },
  {
    id: 'page-journalist',
    title: 'For Journalists',
    description: 'Verified story angles, press-ready statistics, and source contacts.',
    category: 'Page',
    href: '/for/journalist',
    icon: '📰',
    tags: ['journalist', 'press', 'media', 'story', 'verified', 'stats'],
  },
  {
    id: 'page-faq',
    title: 'Frequently Asked Questions',
    description: 'Answers to the most common questions about KWIN City.',
    category: 'Page',
    href: '/faq',
    icon: '❓',
    tags: ['faq', 'questions', 'help', 'answers', 'guide'],
  },
  {
    id: 'page-downloads',
    title: 'Document Downloads',
    description: 'Official reports, policy documents, data sheets, and project briefs — all in one place.',
    category: 'Page',
    href: '/downloads',
    icon: '📥',
    tags: ['download', 'documents', 'pdf', 'reports', 'policy', 'briefs'],
  },
  {
    id: 'page-updates',
    title: 'KWIN Updates',
    description: 'Official milestones, portal additions, and project news from the KWIN City team.',
    category: 'Page',
    href: '/updates',
    icon: '📡',
    tags: ['updates', 'news', 'milestones', 'announcements', 'changelog', 'latest'],
  },
];

// ─── Timeline Phases ──────────────────────────────────────────────────────────
const TIMELINE_ENTRIES: SearchEntry[] = [
  {
    id: 'timeline-0',
    title: 'Phase 0 — Inauguration & Land Acquisition (2024)',
    description: 'Official launch, KIADB approvals, initial land demarcation, and master plan disclosure.',
    category: 'Timeline',
    href: '/timeline',
    icon: '🎉',
    tags: ['inauguration', 'land acquisition', 'kiadb', '2024', 'phase 0', 'launch'],
  },
  {
    id: 'timeline-1',
    title: 'Phase 1 — Infrastructure & Connectivity (2025)',
    description: 'Road network, STRR connectivity framework, water supply systems, and electrical grid planning.',
    category: 'Timeline',
    href: '/timeline',
    icon: '🔧',
    tags: ['infrastructure', 'roads', 'STRR', 'connectivity', '2025', 'phase 1'],
  },
  {
    id: 'timeline-2',
    title: 'Phase 2 — Institutional & Knowledge District (2026)',
    description: 'University partnerships, research center preparation, healthcare groundwork, and knowledge district zoning.',
    category: 'Timeline',
    href: '/timeline',
    icon: '🎓',
    tags: ['university', 'knowledge district', 'research', '2026', 'phase 2', 'education'],
  },
  {
    id: 'timeline-3',
    title: 'Phase 3 — Industrial & Revenue Generation (2027)',
    description: 'Semiconductor park land release, aerospace cluster, solar farm, and industrial allotments.',
    category: 'Timeline',
    href: '/timeline',
    icon: '🏭',
    tags: ['industrial', 'semiconductor', 'aerospace', 'solar', '2027', 'phase 3'],
  },
  {
    id: 'timeline-4',
    title: 'Phase 4 — Wellbeing & Sustainability (2028)',
    description: 'Lake restoration, green building standards, health-tech hub, and urban heat island mitigation.',
    category: 'Timeline',
    href: '/timeline',
    icon: '🌿',
    tags: ['wellbeing', 'sustainability', 'lakes', 'green', '2028', 'phase 4', 'health'],
  },
  {
    id: 'timeline-5',
    title: 'Phase 5 — Full Operational Status (2030)',
    description: 'Industrial clusters operational, 100,000+ jobs, net-zero carbon, world-class amenities.',
    category: 'Timeline',
    href: '/timeline',
    icon: '🌟',
    tags: ['operational', 'jobs', 'net zero', '2030', 'phase 5', 'complete'],
  },
];

// ─── Sectors ─────────────────────────────────────────────────────────────────
const SECTOR_ENTRIES: SearchEntry[] = [
  {
    id: 'sector-semiconductor',
    title: 'Semiconductor Manufacturing',
    description: 'Advanced chip manufacturing, wafer production, and design services — 25,000 projected jobs.',
    category: 'Sector',
    href: '/sectors',
    icon: '💾',
    tags: ['semiconductor', 'chips', 'wafer', 'manufacturing', 'microelectronics', 'fab'],
  },
  {
    id: 'sector-aerospace',
    title: 'Aerospace & Defence',
    description: 'Aircraft manufacturing, avionics, and defence systems — 15,000 projected jobs.',
    category: 'Sector',
    href: '/sectors',
    icon: '✈️',
    tags: ['aerospace', 'defence', 'aircraft', 'avionics', 'manufacturing'],
  },
  {
    id: 'sector-healthtech',
    title: 'Health-Tech & Medical',
    description: 'Biotech research, medical devices, and telemedicine — 20,000 projected jobs.',
    category: 'Sector',
    href: '/sectors',
    icon: '🏥',
    tags: ['healthcare', 'health tech', 'medical', 'biotech', 'devices', 'telemedicine'],
  },
  {
    id: 'sector-ict',
    title: 'Information & Communication Technology',
    description: 'Cloud computing, AI/ML, and software development — 30,000 projected jobs.',
    category: 'Sector',
    href: '/sectors',
    icon: '💻',
    tags: ['ict', 'software', 'ai', 'cloud', 'technology', 'it', 'digital'],
  },
  {
    id: 'sector-renewable',
    title: 'Renewable Energy & Green Tech',
    description: 'Solar manufacturing, battery technology, and EV components — 10,000 projected jobs.',
    category: 'Sector',
    href: '/sectors',
    icon: '☀️',
    tags: ['renewable energy', 'solar', 'battery', 'ev', 'green tech', 'clean energy'],
  },
];

// ─── FAQ entries (mirrored from faq.json) ────────────────────────────────────
const FAQ_ENTRIES: SearchEntry[] = [
  {
    id: 'faq-what-is-kwin',
    title: 'What is KWIN City?',
    description: 'KWIN stands for Knowledge, Wellbeing, and Innovation — a proposed 465-acre integrated township in Doddaballapura, North Bengaluru.',
    category: 'FAQ',
    href: '/faq#general',
    icon: '❓',
    tags: ['kwin', 'what is', 'overview', 'general', 'doddaballapura'],
  },
  {
    id: 'faq-kiadb',
    title: 'What is KIADB and what is its role?',
    description: 'Karnataka Industrial Areas Development Board (KIADB) is the state agency that develops and manages industrial areas including KWIN City land.',
    category: 'FAQ',
    href: '/faq#general',
    icon: '🏛️',
    tags: ['kiadb', 'government', 'karnataka', 'industrial areas', 'board'],
  },
  {
    id: 'faq-invest',
    title: 'How can I invest in KWIN City?',
    description: 'Investment pathways include land allotment through KIADB, sector-specific industrial clusters, and partner programs. Expressions of interest are through the official KIADB portal.',
    category: 'FAQ',
    href: '/faq#investor',
    icon: '📈',
    tags: ['invest', 'investor', 'land allotment', 'opportunities', 'eoi'],
  },
  {
    id: 'faq-when-complete',
    title: 'When will KWIN City be complete?',
    description: 'Full operational status is targeted for 2030 across 5 development phases. Phase 0 (inauguration) was completed in 2024.',
    category: 'FAQ',
    href: '/faq#general',
    icon: '📅',
    tags: ['timeline', 'completion', '2030', 'phases', 'schedule'],
  },
  {
    id: 'faq-jobs',
    title: 'How many jobs will KWIN City create?',
    description: '100,000+ direct jobs are targeted across all sectors by 2030, though this figure is pending primary source verification.',
    category: 'FAQ',
    href: '/faq#general',
    icon: '👔',
    tags: ['jobs', 'employment', 'careers', 'workforce'],
  },
];

// ─── Downloads (mirrored from downloads.json) ────────────────────────────────
const DOWNLOAD_ENTRIES: SearchEntry[] = [
  {
    id: 'dl-kiadb-notification',
    title: 'KIADB Official Project Notification',
    description: 'Official Karnataka Industrial Areas Development Board notification for KWIN City designation.',
    category: 'Download',
    href: '/downloads',
    icon: '📄',
    tags: ['kiadb', 'official', 'government', 'notification', 'pdf', 'verified'],
  },
  {
    id: 'dl-project-brief',
    title: 'KWIN City Project Brief',
    description: 'Overview document covering the three pillars, investment vision, and projected employment numbers.',
    category: 'Download',
    href: '/downloads',
    icon: '📋',
    tags: ['brief', 'overview', 'investment', 'pillars', 'project summary'],
  },
  {
    id: 'dl-opencity-data',
    title: 'Bengaluru Aviation Traffic Open Dataset',
    description: 'CKAN dataset from OpenCity.in used in the Data Insights Lab — Kempegowda Airport traffic data.',
    category: 'Download',
    href: '/downloads',
    icon: '✈️',
    tags: ['data', 'aviation', 'airport', 'opencity', 'csv', 'open data'],
  },
];

// ─── Sustainability entries ──────────────────────────────────────────────────
const SUSTAINABILITY_ENTRIES: SearchEntry[] = [
  {
    id: 'sus-green-cover',
    title: 'Green Cover Target — 40% of total area',
    description: '40% of KWIN City area to be maintained as green cover by 2030.',
    category: 'Sustainability',
    href: '/sustainability',
    icon: '🌳',
    tags: ['green', 'cover', 'trees', 'parks', 'environment', '40 percent'],
  },
  {
    id: 'sus-net-zero',
    title: 'Net-Zero Carbon by 2030',
    description: 'KWIN City targets carbon neutrality across all operational energy by 2030.',
    category: 'Sustainability',
    href: '/sustainability',
    icon: '♻️',
    tags: ['net zero', 'carbon neutral', 'emissions', 'climate', '2030'],
  },
  {
    id: 'sus-water',
    title: 'Water Recycling — 80% target',
    description: '80% of wastewater treated and reused by 2029 via integrated water management.',
    category: 'Sustainability',
    href: '/sustainability',
    icon: '💧',
    tags: ['water', 'recycling', 'wastewater', 'conservation', 'lakes'],
  },
  {
    id: 'sus-energy',
    title: 'Renewable Energy — 100% operational target',
    description: 'All operational energy to be sourced from renewables, anchored by the 465-acre solar farm.',
    category: 'Sustainability',
    href: '/sustainability',
    icon: '☀️',
    tags: ['renewable', 'solar', 'energy', '100 percent', 'clean'],
  },
];

// ─── Pillars ──────────────────────────────────────────────────────────────────
const PILLAR_ENTRIES: SearchEntry[] = [
  {
    id: 'pillar-knowledge',
    title: 'Pillar: Knowledge — Research & Innovation Hub',
    description: 'Higher education zones, R&D centers, university collaboration areas, and innovation incubation hubs.',
    category: 'Pillar',
    href: '/about',
    icon: '🎓',
    tags: ['knowledge', 'research', 'university', 'education', 'innovation', 'r&d', 'stem'],
  },
  {
    id: 'pillar-wellbeing',
    title: 'Pillar: Wellbeing — Health, Sustainability & Living',
    description: 'Integrated healthcare, green spaces, interconnected lakes, sustainable living, and urban parks.',
    category: 'Pillar',
    href: '/about',
    icon: '🌿',
    tags: ['wellbeing', 'health', 'green', 'parks', 'lakes', 'sustainable', 'living'],
  },
  {
    id: 'pillar-innovation',
    title: 'Pillar: Innovation — Industry Clusters & Tech',
    description: 'Semiconductor park, aerospace cluster, solar farm, advanced manufacturing, and digital hubs.',
    category: 'Pillar',
    href: '/about',
    icon: '⚡',
    tags: ['innovation', 'industry', 'semiconductor', 'aerospace', 'manufacturing', 'tech'],
  },
];

// ─── All entries combined ─────────────────────────────────────────────────────
export const SEARCH_INDEX: SearchEntry[] = [
  ...PAGES,
  ...TIMELINE_ENTRIES,
  ...SECTOR_ENTRIES,
  ...FAQ_ENTRIES,
  ...DOWNLOAD_ENTRIES,
  ...SUSTAINABILITY_ENTRIES,
  ...PILLAR_ENTRIES,
];

// ─── Scoring & querying ───────────────────────────────────────────────────────
function scoreEntry(entry: SearchEntry, query: string): number {
  const q = query.toLowerCase().trim();
  const words = q.split(/\s+/).filter(Boolean);
  if (!words.length) return 0;

  let score = 0;
  const titleLower = entry.title.toLowerCase();
  const descLower = entry.description.toLowerCase();
  const tagsJoined = entry.tags.join(' ').toLowerCase();

  for (const word of words) {
    // Exact title match bonus
    if (titleLower === word) score += 10;
    else if (titleLower.includes(word)) score += 7;

    if (tagsJoined.includes(word)) score += 4;
    if (descLower.includes(word)) score += 2;

    // Category name hit
    if (entry.category.toLowerCase().includes(word)) score += 3;
  }

  return score;
}

/** Returns deduplicated, scored results sorted by relevance. Max 20 results. */
export function querySearchIndex(query: string, limit = 20): SearchEntry[] {
  if (!query.trim()) return [];

  return SEARCH_INDEX.map((entry) => ({ entry, score: scoreEntry(entry, query) }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ entry }) => entry);
}

/** Returns top entries from each category for the empty-state "popular" view. */
export function getPopularEntries(): SearchEntry[] {
  const popular = [
    'page-about', 'page-investor', 'page-timeline', 'page-data',
    'sector-semiconductor', 'page-faq', 'page-downloads', 'page-updates',
  ];
  return SEARCH_INDEX.filter((e) => popular.includes(e.id));
}

export const CATEGORY_COLORS: Record<SearchCategory, string> = {
  Page:           'bg-blue-50 text-blue-700 border-blue-100',
  Timeline:       'bg-purple-50 text-purple-700 border-purple-100',
  Sector:         'bg-amber-50 text-amber-700 border-amber-100',
  Sustainability: 'bg-emerald-50 text-emerald-700 border-emerald-100',
  Pillar:         'bg-cyan-50 text-cyan-700 border-cyan-100',
  FAQ:            'bg-rose-50 text-rose-700 border-rose-100',
  Download:       'bg-gray-50 text-gray-700 border-gray-200',
  Update:         'bg-indigo-50 text-indigo-700 border-indigo-100',
  Data:           'bg-teal-50 text-teal-700 border-teal-100',
};
