/**
 * Canonical public-route inventory for browser-level contracts.
 *
 * Add a route here when it becomes publicly navigable; smoke, contrast, and
 * future visual-contract suites will then exercise the same coverage.
 */
export const PUBLIC_ROUTES = [
  "/",
  "/about",
  "/aarti-s-ravikumar",
  "/account",
  "/analytics",
  "/community",
  "/contact",
  "/data-insights",
  "/download",
  "/downloads",
  "/evidence",
  "/evidence-library",
  "/faq",
  "/for",
  "/for/curious-citizens",
  "/for/investor",
  "/for/journalist",
  "/for/researcher",
  "/for/resident",
  "/news-intelligence",
  "/news-reader",
  "/offline",
  "/region-map",
  "/search?q=kwin",
  "/sectors",
  "/sectors/comparison",
  "/sources",
  "/sustainability",
  "/terms",
  "/timeline",
  "/tools",
  "/tools/accessibility",
  "/tools/investment-radar",
  "/tools/open-data-studio",
  "/tools/opportunity-exchange",
  "/tools/regulatory-navigator",
  "/tools/risk-check",
  "/tools/spatial-explorer",
  "/tools/valuation-index",
  "/trust",
  "/updates",
  "/updates/change-tracker",
  "/updates/regulatory-news",
  "/updates/satellite-tracker",
  "/why-north-bengaluru",
] as const;
