import React, { useState } from 'react';
import { X, Copy, Check, Download, FileText, Printer } from 'lucide-react';
import { EvaluationPillar } from '../types';

interface ReportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  compositeScore: number;
  pillars: EvaluationPillar[];
  weights: Record<string, number>;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({
  isOpen,
  onClose,
  compositeScore,
  pillars,
  weights,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = () => {
    return `# Comprehensive Website Evaluation & Audit Report: https://kwin-city.com/
**Audit Target:** https://kwin-city.com/
**Subject:** KWIN City Independent Research & Spatial Intelligence Platform
**Composite Score:** ${compositeScore.toFixed(1)} / 10 (Grade: B+ / Good with Key Governance Caveats)
**Date:** September 2026

---

## Executive Summary
https://kwin-city.com/ is an independent spatial research and corridor intelligence platform focused on North Bengaluru's 5,800-acre Knowledge, Wellbeing, and Innovation (KWIN) City project.

### Overall Rating: ${compositeScore.toFixed(1)} / 10
- **Strengths:** High-value consolidation of spatial masterplans (Doddaballapur, Dabaspet, STRR), modern Progressive Web App (PWA) architecture with offline caching, clean editorial typography, and structured corridor dossiers.
- **Critical Vulnerabilities:** High risk of visitor confusion with official Government of Karnataka channels due to domain naming, absence of prominent disclaimer banners, anonymous editorial masthead, and unclarified commercial/brokerage relationships.

---

## Pillar-by-Pillar Audit Breakdown
${pillars
  .map(
    (p) => `### ${p.name}
- **Score:** ${p.score.toFixed(1)} / 10 (Weight: ${weights[p.id] ?? p.defaultWeight}%)
- **Verdict:** ${p.verdict}
- **Summary:** ${p.summary}
- **Key Strengths:**
${p.strengths.map((s) => `  * ${s}`).join('\n')}
- **Weaknesses & Risks:**
${p.weaknesses.map((w) => `  * ${w}`).join('\n')}
- **Priority Recommendations:**
${p.recommendations.map((r) => `  * ${r}`).join('\n')}
`
  )
  .join('\n')}

---

## Comparative Benchmark
- **kwin-city.com:** Best-in-class spatial synthesis and modern PWA reading experience, but lacks statutory authority.
- **Official Karnataka Govt (KIADB / State):** Authoritative legal documents (RTC, Section 28 gazettes), but fragmented across archaic portals and PDF files.
- **Commercial Real Estate Aggregators:** Plagued with advertising bias and broker spam; lacks macro urban planning rigor.

---

## Recommended Action Plan to Reach 9.0+ / 10
1. **Immediate (Days 1-7):** Add persistent top disclaimer: "Independent Research Portal — Not Affiliated with Government of Karnataka or KIADB".
2. **Short-Term (Days 8-30):** Publish named editorial board, author credentials, and conflict-of-interest disclosure.
3. **Mid-Term (Days 31-60):** Integrate direct links to official Bhoomi / Kaveri 2.0 / KIADB gazettes and provide vector GIS cadastral overlays.

---
*Report generated by KWIN City Independent Audit Suite.*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([generateMarkdown()], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = 'kwin-city-com-website-evaluation.md';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-3xl w-full max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-teal-400" />
            <h3 className="text-lg font-bold text-white">Full Executive Audit Report</h3>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 rounded-lg transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Box */}
        <div className="p-6 overflow-y-auto flex-1 font-mono text-xs text-slate-300 bg-slate-950/40 leading-relaxed whitespace-pre-wrap selection:bg-teal-500 selection:text-white">
          {generateMarkdown()}
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 bg-slate-950 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="text-xs text-slate-400">
            Format: Standard Markdown (.md)
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition"
            >
              <Download className="w-3.5 h-3.5" /> Download .md
            </button>
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-teal-600 hover:bg-teal-500 text-white text-xs font-semibold shadow-sm transition"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied to Clipboard' : 'Copy Full Markdown'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
