-- KWIN City Portal: initial PostgreSQL schema
--
-- This migration is intentionally idempotent so it can bootstrap an existing
-- Supabase project. Future changes belong in a new, ordered migration file.
-- Do not edit this file after it has been applied to a shared environment.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
  id text PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  password_salt text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_preferences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE REFERENCES public.users(email) ON DELETE CASCADE,
  persona text NOT NULL DEFAULT 'citizen',
  favorite_topics text[] NOT NULL DEFAULT '{}',
  digest_frequency text NOT NULL DEFAULT 'weekly',
  email_updates boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_preferences_persona_check
    CHECK (persona IN ('investor', 'resident', 'researcher', 'journalist', 'citizen')),
  CONSTRAINT user_preferences_digest_frequency_check
    CHECK (digest_frequency IN ('daily', 'weekly', 'monthly'))
);

CREATE TABLE IF NOT EXISTS public.discussion_posts (
  id text PRIMARY KEY,
  author text NOT NULL,
  title text NOT NULL,
  text text NOT NULL,
  likes integer NOT NULL DEFAULT 0 CHECK (likes >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.discussion_replies (
  id text PRIMARY KEY,
  post_id text NOT NULL REFERENCES public.discussion_posts(id) ON DELETE CASCADE,
  author text NOT NULL,
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.newsletter_signups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text,
  interests text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.seo_agency_runs (
  id text PRIMARY KEY,
  run_date date NOT NULL UNIQUE,
  generated_at timestamptz NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.value_add_alert_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  persona text NOT NULL,
  topics text[] NOT NULL DEFAULT '{}',
  geofilters text[] NOT NULL DEFAULT '{}',
  cadence text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT value_add_alert_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS public.value_add_export_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  export_type text NOT NULL,
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'queued',
  file_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  CONSTRAINT value_add_export_expiry_check CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE TABLE IF NOT EXISTS public.value_add_opportunity_leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  role text NOT NULL,
  requirement text NOT NULL,
  budget_band text,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_user_preferences_email ON public.user_preferences(email);
CREATE INDEX IF NOT EXISTS idx_discussion_posts_created_at ON public.discussion_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_discussion_replies_post_id_created_at ON public.discussion_replies(post_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_newsletter_signups_created_at ON public.newsletter_signups(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_seo_agency_runs_generated_at ON public.seo_agency_runs(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_value_add_alerts_email ON public.value_add_alert_subscriptions(email);
CREATE INDEX IF NOT EXISTS idx_value_add_alerts_status ON public.value_add_alert_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_value_add_exports_created_at ON public.value_add_export_jobs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_value_add_exports_status ON public.value_add_export_jobs(status);
CREATE INDEX IF NOT EXISTS idx_value_add_leads_created_at ON public.value_add_opportunity_leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_value_add_leads_role ON public.value_add_opportunity_leads(role);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_users_updated_at ON public.users;
CREATE TRIGGER set_users_updated_at BEFORE UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS set_user_preferences_updated_at ON public.user_preferences;
CREATE TRIGGER set_user_preferences_updated_at BEFORE UPDATE ON public.user_preferences
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS set_discussion_posts_updated_at ON public.discussion_posts;
CREATE TRIGGER set_discussion_posts_updated_at BEFORE UPDATE ON public.discussion_posts
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS set_discussion_replies_updated_at ON public.discussion_replies;
CREATE TRIGGER set_discussion_replies_updated_at BEFORE UPDATE ON public.discussion_replies
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS set_value_add_alerts_updated_at ON public.value_add_alert_subscriptions;
CREATE TRIGGER set_value_add_alerts_updated_at BEFORE UPDATE ON public.value_add_alert_subscriptions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.increment_post_likes(post_id text)
RETURNS integer
LANGUAGE sql
AS $$
  UPDATE public.discussion_posts
  SET likes = likes + 1
  WHERE id = post_id
  RETURNING likes;
$$;

-- The API performs authorization and uses the server-only service role key.
-- RLS is enabled with no public policies: browser/anon clients cannot read or
-- mutate private records. The service role bypasses RLS on the server.
DROP POLICY IF EXISTS "Enable read access for all users" ON public.discussion_posts;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.discussion_replies;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.discussion_posts;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.discussion_replies;
DROP POLICY IF EXISTS "Enable like updates" ON public.discussion_posts;
DROP POLICY IF EXISTS "Enable read access for users" ON public.users;
DROP POLICY IF EXISTS "Enable insert access for users" ON public.users;
DROP POLICY IF EXISTS "Enable update access for users" ON public.users;
DROP POLICY IF EXISTS "Enable read access for preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Enable insert access for preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Enable update access for preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Enable read access for SEO agency runs" ON public.seo_agency_runs;
DROP POLICY IF EXISTS "Enable read access for value add alerts" ON public.value_add_alert_subscriptions;
DROP POLICY IF EXISTS "Enable insert access for value add alerts" ON public.value_add_alert_subscriptions;
DROP POLICY IF EXISTS "Enable update access for value add alerts" ON public.value_add_alert_subscriptions;
DROP POLICY IF EXISTS "Enable read access for value add exports" ON public.value_add_export_jobs;
DROP POLICY IF EXISTS "Enable insert access for value add exports" ON public.value_add_export_jobs;
DROP POLICY IF EXISTS "Enable update access for value add exports" ON public.value_add_export_jobs;
DROP POLICY IF EXISTS "Enable read access for value add leads" ON public.value_add_opportunity_leads;
DROP POLICY IF EXISTS "Enable insert access for value add leads" ON public.value_add_opportunity_leads;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_signups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seo_agency_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.value_add_alert_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.value_add_export_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.value_add_opportunity_leads ENABLE ROW LEVEL SECURITY;
